title: "ArduinoとMobiFlightで作る! Microsoft Flight Simulator ホームコックピット"
summary: "概要概要"
topics: [arduino, 電子工作]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - getting-started
  - installation
  - parking-break-led
  - parking-break-switch
  - com-radio-7seg-led
  - com-radio-rotary-encoder
  - throttle-volume-resistor
  - flap-servomotor
  - air-speed-stepper-motor
  - air-speed-lcd
